/** Labels for sex — stored as displayed (stable-friendly). */
export const HORSE_GENDERS = [
  "Mare",
  "Stallion",
  "Gelding",
  "Colt",
  "Filly",
  "Rig (cryptorchid)",
  "Unknown",
] as const;

/** Physical / type category (not training level). */
export const HORSE_CATEGORIES = [
  "Riding horse",
  "Sport horse",
  "Pony",
  "Small pony / children's pony",
  "Draft horse",
  "Miniature horse",
  "Gaited horse",
  "Mule / hinny",
  "Donkey",
  "Other",
] as const;

/** Common coat colours — users can still type custom values via datalist + input. */
export const HORSE_COAT_COLORS = [
  "Bay",
  "Dark bay",
  "Brown",
  "Black",
  "Chestnut",
  "Sorrel",
  "Liver chestnut",
  "Grey",
  "Dapple grey",
  "Fleabitten grey",
  "Rose grey",
  "Palomino",
  "Buckskin",
  "Dun",
  "Red dun",
  "Grullo",
  "Perlino",
  "Cremello",
  "Smoky black",
  "Smoky cream",
  "Champagne",
  "Silver dapple / silver bay",
  "Rabicano",
  "Roan (mixed)",
  "Red roan",
  "Bay roan",
  "Blue roan",
  "Strawberry roan",
  "Frame overo",
  "Splash white",
  "Sabino",
  "Tobiano",
  "Leopard / Appaloosa pattern",
  "Few spot Appaloosa",
  "Blanket Appaloosa",
  "Piebald",
  "Skewbald",
  "Pinto (mixed)",
  "Sooty",
  "Other / mixed colour",
] as const;

/** Common breeds & types — free text also allowed via datalist. */
export const HORSE_BREEDS = [
  "Warmblood (generic)",
  "Dutch Warmblood (KWPN)",
  "Belgian Warmblood (BWP)",
  "Danish Warmblood",
  "Swedish Warmblood",
  "Hanoverian",
  "Holsteiner",
  "Oldenburg",
  "Westphalian",
  "Mecklenburg",
  "Rhinelander",
  "Selle Français",
  "Zangersheide",
  "AES (Anglo European Studbook)",
  "Irish Sport Horse",
  "British Warmblood",
  "Trakehner",
  "Thoroughbred",
  "Anglo-Arabian",
  "Arabian",
  "Andalusian / PRE",
  "Lusitano",
  "Friesian",
  "Irish Draught",
  "Cleveland Bay",
  "Welsh Pony (Section A)",
  "Welsh Pony (Section B)",
  "Welsh Pony (Section C)",
  "Welsh Pony (Section D)",
  "Connemara Pony",
  "Shetland Pony",
  "New Forest Pony",
  "Dartmoor Pony",
  "Exmoor Pony",
  "Highland Pony",
  "Dales Pony",
  "Fell Pony",
  "Haflinger",
  "Icelandic Horse",
  "Norwegian Fjord",
  "Quarter Horse",
  "American Paint Horse",
  "Appaloosa",
  "Morgan",
  "Standardbred",
  "Tennessee Walking Horse",
  "Missouri Fox Trotter",
  "Paso Fino",
  "Peruvian Paso",
  "Rocky Mountain Horse",
  "Clydesdale",
  "Shire",
  "Percheron",
  "Belgian Draught",
  "Suffolk Punch",
  "Australian Stock Horse",
  "American Mustang",
  "Pony of the Americas",
  "Miniature Horse",
  "Grade / crossbred",
  "Other",
] as const;
